### ISSUE TITLE
Hash#path_to_key(key)

### ISSUE THREAD

**Issue by rudy-on-rails** [ko1/rubyhackchallenge#44]
`Hash#path_to_key` returns an `Array` with the `path` towards getting to a certain `key` within a certain `Hash` structure as follow:

```ruby
hash = {
  a: {
    b: {
      c: 1
    }
  }
}

result = hash.path_to_key(:c)
result == [:a, :b]
```

**Comment by rudywseidinger** [comment]
https://github.com/ruby/ruby/pull/1847/files
