### ISSUE TITLE
テストを追加後の図について

### ISSUE THREAD

**Issue by yui-knk** [ko1/rubyhackchallenge#48]
https://github.com/ko1/rubyhackchallenge/blob/master/JA/6_coverage.md#arraysecond-%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B

> 無事青くなりました。きちんとテストできていることが確認できて、安心できますね。

の直前の図が、テスト追加前の図と同じになっています。

**Comment by mame** [comment]
ありがとうございます！
