### ISSUE TITLE
Cannot build latest ruby with `autoconf`

### ISSUE THREAD

**Issue by okuramasafumi** [ko1/rubyhackchallenge#78]
https://bugs.ruby-lang.org/issues/17723
Due to `autoconf` issue, following the instruction on this repository is not finished successfully. When running `configure` command it prints `configure: error: cannot find required auxiliary files: config.guess config.sub`.

https://bugs.ruby-lang.org/projects/ruby-master/repository/git/revisions/4250d7c910fd67c0da07c6213901009330e3cd51
This commit introduced the file named `autogen.sh` and I confirmed that it works with the latest ruby.

I'll open a PR to fix the document when this issue is confirmed.

**Comment by mame** [comment]
Good catch! Yes, now `./autogen.sh` is needed instead of `autoconf`. I'll be happy to merge a PR if you could create. Thanks!

**Comment by mame** [comment]
Ah, `apt-get install automake` might be also needed, but I'm not 100% unsure

**Comment by okuramasafumi** [comment]
https://github.com/ko1/rubyhackchallenge/blob/master/JA/2_mri_structure.md#L70
I found that in JA version it explicitly says "it uses autoconf". Now is that correct? I saw the script and it seems using `autoreconf`.

**Comment by mame** [comment]
Now we have to use autoreconf because autoconf 2.70, which was released in the last December, has an incompatibility.

**Comment by okuramasafumi** [comment]
I see, so we need to replace that "autoconf" with "autoreconf".
